/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof import('./../views/Category/index.vue')['default']
    copy: typeof import('./../views/Home/components/HomeCategory copy.vue')['default']
    Detail: typeof import('./../views/Detail/index.vue')['default']
    DetailHot: typeof import('./../views/Detail/components/DetailHot.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Gooditem: typeof import('./../views/Home/components/Gooditem.vue')['default']
    GoodItem: typeof import('./../views/Home/components/GoodItem.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../views/Home/index.vue')['default']
    HomeBanner: typeof import('./../views/Home/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./../views/Home/components/HomeCategory.vue')['default']
    HomeHot: typeof import('./../views/Home/components/HomeHot.vue')['default']
    HomeNew: typeof import('./../views/Home/components/HomeNew.vue')['default']
    HomePanel: typeof import('./../views/Home/components/HomePanel.vue')['default']
    HomeProduct: typeof import('./../views/Home/components/HomeProduct.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    ImgView: typeof import('./../components/imgView/index.vue')['default']
    LayouNav: typeof import('./../views/Layout/components/LayouNav.vue')['default']
    Layout: typeof import('./../views/Layout/index.vue')['default']
    LayoutFixed: typeof import('./../views/Layout/components/LayoutFixed.vue')['default']
    LayoutFooter: typeof import('./../views/Layout/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./../views/Layout/components/LayoutHeader.vue')['default']
    Login: typeof import('./../views/Login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategory: typeof import('./../views/subCategory/index.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
