/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof import('./../views/Category/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../views/Home/index.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    LayouNav: typeof import('./../views/Layout/components/LayouNav.vue')['default']
    Layout: typeof import('./../views/Layout/index.vue')['default']
    LayoutFooter: typeof import('./../views/Layout/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./../views/Layout/components/LayoutHeader.vue')['default']
    Login: typeof import('./../views/Login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
